$pdf_mode = 1;
$out_dir = 'build';
$aux_dir = 'build';
$pdflatex = 'pdflatex -interaction=nonstopmode -synctex=1 -shell-escape %O %S';
@clean_ext = (@clean_ext, 'synctex.gz', 'bbl', 'blg', 'run.xml', 'bcf');
$preview_continuous = 1;
$bibtex = 'bibtex %O %S';
$biber = 'biber %O %S';
$pdf_previewer = 'start';
$failure_cmd = 'echo Compilation failed!';